### ISSUE TITLE
Přidat LN donate na web

### ISSUE THREAD

**Issue by pavelkukla** [pavelkukla/kryptodoupe.cz#10]
prý bych to tam měl mít, sos

**Comment by iWarpBTC** [comment]
Můžu nabídnout své LNbits https://pay.btcslovnik.cz/. Aktuální remote balance 286k sats.

**Comment by JakubSlovak** [comment]
Uvažoval jsem o tom LN donate.
Pravděpodobně nejsnadnější varianta jak toho docílit je podobně jako má iwarp. Problém je, že ty nemáš uzel, takže budeš muset někomu věřit. Já jsem za torem a moc nevím jak by se to dalo vyřešit. Napadá mě iwarp který by ti to mohl zprostředkovat (ale nemá nejlepší likviditu). Pravděpodobně bych k němu mohl otevřít nějaký větší kanál a byl by klid.

Haxi, prakticky by sis tam ( [u iwarpa](https://pay.btcslovnik.cz/) ) jenom založil účet, někam si uložil URL stránku (to je totiž klíč ke všem tvým přijatým satoshis), mohl by sis je sám pak vybírat na peněženku když by ti něco přišlo.) pak bys šel do Manage extension, TPoS, a vytvořil nový TPoS, a ten by sis mohl už přidělat na webovky. Vypadalo by to pak nějak takto: https://btc-slovnik.cz/pages/donate.html

**Comment by pavelkukla** [comment]
@JakubSlovak na kolik by mě vyšel vlastní uzel? Asi bych neměl problém tady něco spustit. Popřípadě co kdybych to dal na prasáka přes BlueWallet? :D Jen se ptám, nemám problém to udělat přes iWarpa.

**Comment by dvorakh1997** [comment]
Normální uzel z nových součástek složíš kolem 6,000 Kč. Nevyplatí se to. Řekl bych, že nejschůdnejší to bude přes iWarpův LNbits... Tam jde vytvořit i separátní walletka, takže se vám nebude nic motat dohromady.

**Comment by JakubSlovak** [comment]
přesně tak.

bluewallet nic takového neumí. LNbits nebo BTCPay jsou jediné možnosti.

**Comment by pavelkukla** [comment]
Ok, mělo by to fungovat, dám na web https://pay.btcslovnik.cz/tpos/7YMNA2GoHjdmV2WTtvpP6K
