### ISSUE TITLE
Lze uhádnout seed/může mít někdo vygenerovaný stejný seed jako já?

### ISSUE THREAD

**Issue by pavelkukla** [pavelkukla/kryptodoupe.cz#15]
viz title, nová položka do faq

**Comment by dvorakh1997** [comment]
@pavelkukla issue k revizi, dal jsem to do 1_uvod... Tohle by chtělo ještě nějak definovat, kam co patří.. Mám to přesunout do 5_dalsi?

**Comment by pavelkukla** [comment]
@dvorakh1997 imo 3_peněženky, tam se nejvíc bavíme o semeni

**Comment by dvorakh1997** [comment]
prosím o zavření, vyřešno

**Comment by pavelkukla** [comment]
test
