### ISSUE TITLE
názvy

### ISSUE THREAD

**Issue by gorrdy** [pavelkukla/kryptodoupe.cz#21]
1.
Jak koupit Bitcoin -> Bitcoin
Základy Lightning network -> Lightning network
(tímhle myslím spíš tu adresářovou strukturu)

2.
Proč tam dáváme to "Jak koupit Bitcoin?" I na té hlavní stránce... záměr webu to přece není. Mohlo by to vést trochu ke zmatení, že si jde člověk přečíst jen o tom, jak to bitcoiny koupit.

**Comment by pavelkukla** [comment]
1. V mých očích to nebude to vypadat dobře a nemyslím si, že tohle budou poslední stránky na téma btc a ln, které budeme připravovat. Ničemu delší URL nevadí a nevidím přínos v tom to takhle zkracovat. Stejně se tam většinou jen proklikáš z webu. Pak budeš mít např. /bitcoin, /vzdelavaci-materialy-o-bitcoinu, /platby-v-bitcoinu.... Proč to jedno je jenom /bitcoin? :D Kratší url řeší zkracovače jako bitly.

2. Protože to je mířené především na BFU a záměrem má být někoho navést k tomu, jak koupit bitcoin. S touhle myšlenkou se i stránka připravovala, co nejjednodušeji vysvětlit někomu, co to je, kde to koupím a co s tím mám dělat. FAQ je jen další přidanou hodnotou (kromě zjednodušených informací), díky čemu potenciálně získáme další lidi do sekty. :D „Úvod“ už evokuje overly vzdělávací web, nebo content viz Kicom – není to straightforward to, co potřebuju. To je můj dojem. Furt to jsou hlavně zjednodušené a osekané informace.

**Comment by pavelkukla** [comment]
// pokud si myslíte, že nad tím uvažuju blbě, tak to do mě normálně perte :D
