### ISSUE TITLE
testovaci issue

### ISSUE THREAD

**Issue by dvorakh1997** [pavelkukla/kryptodoupe.cz#5]
tohle je popisek issue, 

tenhle commit zkazil cely web 
16673c244bbf5a5501f1b1365a952617ad0445b2

dávám to na starost @pavelkukla na vyřešení, taky dávám assign této issue na tebe

**Comment by dvorakh1997** [comment]
Tohle jsou pak jen komenty, kde můžem diskutovat o řešení issue

**Comment by pavelkukla** [comment]
budiž vyřešeno
